### ISSUE TITLE
Libc crash on PCSX core

### ISSUE THREAD

**Issue by tytydraco** [Swordfish90/LibretroDroid#26]
Hi again :)

I'm getting a libc crash when the activity recreates itself. Here's the exact error:
`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7150600470 in tid 22163 (er.residentevil), pid 22163 (er.residentevil)`

Using the debugger I ruled out when this happens:
1) Activity starts
2) Rotate the device (causing a configuration change, restarting the app. No big deal, this is intentional)
3) onSaveInstanceState is called
4) onStop and onDestroy are NOT called
5) Error appears and app crashes

I tried this with the other PSX core, mednafen or something. That one fails to even load the game.

I suspect this could be a core issue because I have no such issue when using mgba, nestopia, snes9x, or desmume. I noticed that in Lemuroid you avoid this issue by simply overriding the config changes on rotate, but I'd like to solve it without that method.

Let me know if you think this is an issue with my implementation, your implementation, or the libretro core implementation.

I managed to capture a tombstone of the seg fault:

[tombstone_09.txt](https://github.com/Swordfish90/LibretroDroid/files/5389596/tombstone_09.txt)

**Comment by tytydraco** [comment]
Actually, I do remember that even in RetroArch this core behaved weird on Android. Silent hill crashed RetroArch if you clicked "Quit game".

**Comment by Swordfish90** [comment]
Ah, the rotation issue! A classic on Android. :smile: 

So, the problem here is that with autosave, it really takes ages (read many seconds) to store the state of a modern console (read psp) to disk, so we have to block the UI thread for a very long time. Plus, the state might not even fit the save instance Bundle, which will throw an exception if you exceed a few megabytes of size. My suggestion would be to keep the orientatino changes in these cases.

If you are only using sram and you want to keep a proper orientation management, you could try to understand where the core crashes and why. You can recompile the core yourself using ndk-build (it's pretty straighforward) and use the version contained in "obj/local" which still has debug symbols, this way you can see a proper stacktrace and debug the issues. As an alternative you could import the libretro/pcsx_rearmed project in AndroidStudio using externalNativeBuild and see the stacktrace from the debugger.

**Comment by tytydraco** [comment]
Actually, I even tested without saving the state at all, it still crashes. It is probably core related, but I'll try out your advice! P.S. In my saved instance state override, I actually write to the disk instead of storing it in the instance state. It's a little hacky but it works well to bypass the max size issue. I'll try recompiling the core with debug symbols and see what happens! :)
